# Generated by Django 4.2.6 on 2023-11-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyIPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_ip', models.GenericIPAddressField(editable=False, verbose_name='IP ünvanı')),
            ],
            options={
                'verbose_name': 'Vakansiya IP ünvanı',
                'verbose_name_plural': 'Vakansiya IP ünvanları',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('posoting_date', models.DateField(auto_now_add=True)),
                ('expression_date', models.DateField(auto_now_add=True)),
                ('number_of_view', models.IntegerField()),
                ('job_type', models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('remote', 'Remote')], default='full time', max_length=20)),
                ('level', models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('Team Lead', 'Team Lead')], default='Intern', max_length=30)),
                ('education', models.CharField(choices=[('Higher', 'Higher'), ('Secondary', 'Secondary'), ('Vocational education', 'Vocational Education')], default='Higher', max_length=30)),
                ('job_description', models.TextField()),
                ('company_site_link', models.URLField(verbose_name='Kampaniyanın veb site linki')),
                ('email_address', models.EmailField(max_length=100)),
                ('salary_agreement', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.vacancycategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='career.city')),
                ('viewed_ips', models.ManyToManyField(editable=False, related_name='vacancies', to='career.vacancyips', verbose_name='Vakansiyalar görüntüləndiyi IP ünvanları')),
            ],
        ),
    ]
